// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Policlínico.Infrastructure.Data;

#nullable disable

namespace Policlínico.Infrastructure.Migrations
{
    [DbContext(typeof(PoliclínicoDbContext))]
    partial class PoliclínicoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Policlínico.Domain.Entities.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asignacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsignacion"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajador_id");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_consulta");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("MedicoPrincipalId")
                        .HasColumnType("integer")
                        .HasColumnName("medico_principal_id");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int?>("PuestoMedicoId")
                        .HasColumnType("integer")
                        .HasColumnName("puesto_medico_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("IdConsulta");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("MedicoPrincipalId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PuestoMedicoId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.ConsultaTrabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("integer")
                        .HasColumnName("consulta_id");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajador_id");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("ConsultaTrabajadores");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_departamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("JefeId")
                        .HasColumnType("integer")
                        .HasColumnName("jefe_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdDepartamento");

                    b.HasIndex("JefeId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctores");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaAConsulta", b =>
                {
                    b.Property<int>("IdEntregaConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_entrega_consulta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntregaConsulta"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("integer")
                        .HasColumnName("consulta_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.HasKey("IdEntregaConsulta");

                    b.HasIndex("ConsultaId");

                    b.ToTable("EntregasAConsulta");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaAConsultaDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("EntregaConsultaId")
                        .HasColumnType("integer")
                        .HasColumnName("entrega_consulta_id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.HasKey("IdDetalle");

                    b.HasIndex("EntregaConsultaId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("EntregaAConsultaDetalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaMedicamento", b =>
                {
                    b.Property<int>("IdEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_entrega");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntrega"));

                    b.Property<int>("DepartamentoDestinoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_destino_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<int?>("JefeAlmacenId")
                        .HasColumnType("integer")
                        .HasColumnName("jefe_almacen_id");

                    b.HasKey("IdEntrega");

                    b.HasIndex("DepartamentoDestinoId");

                    b.HasIndex("JefeAlmacenId");

                    b.ToTable("EntregasMedicamentos");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaMedicamentoDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("EntregaId")
                        .HasColumnType("integer")
                        .HasColumnName("entrega_id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.HasKey("IdDetalle");

                    b.HasIndex("EntregaId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("EntregaMedicamentoDetalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StockIdStock")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StockIdStock");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contacto");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_identidad");

                    b.HasKey("IdPaciente");

                    b.HasIndex("NumeroIdentidad")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.PedidoMedicamento", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("integer")
                        .HasColumnName("consulta_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pedido");

                    b.HasKey("IdPedido");

                    b.HasIndex("ConsultaId");

                    b.ToTable("PedidosMedicamentos");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.PedidoMedicamentoDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.HasKey("IdDetalle");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoMedicamentoDetalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.PuestoMedico", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_puesto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPuesto"));

                    b.HasKey("IdPuesto");

                    b.ToTable("PuestosMedicos", (string)null);
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.SolicitudMedicamento", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int?>("JefeDepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("jefe_departamento_id");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("JefeDepartamentoId");

                    b.ToTable("SolicitudesMedicamentos");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.SolicitudMedicamentoDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.HasKey("IdDetalle");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudMedicamentoDetalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_stock");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStock"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.HasKey("IdStock");

                    b.HasIndex("DepartamentoId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Trabajador", b =>
                {
                    b.Property<int>("IdTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trabajador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrabajador"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cargo");

                    b.Property<int?>("ConsultaIdConsulta")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoLaboral")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_laboral");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTrabajador");

                    b.HasIndex("ConsultaIdConsulta");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Asignaciones")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("Asignaciones")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Trabajador", "MedicoPrincipal")
                        .WithMany()
                        .HasForeignKey("MedicoPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Departamento", "PuestoMedico")
                        .WithMany()
                        .HasForeignKey("PuestoMedicoId");

                    b.Navigation("Departamento");

                    b.Navigation("MedicoPrincipal");

                    b.Navigation("Paciente");

                    b.Navigation("PuestoMedico");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.ConsultaTrabajador", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Consulta", "Consulta")
                        .WithMany("AsignacionesConsulta")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("AsignacionesConsulta")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Trabajador", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Jefe");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaAConsulta", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaAConsultaDetalle", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.EntregaAConsulta", "EntregaConsulta")
                        .WithMany("Detalles")
                        .HasForeignKey("EntregaConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntregaConsulta");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaMedicamento", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Departamento", "DepartamentoDestino")
                        .WithMany()
                        .HasForeignKey("DepartamentoDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Trabajador", "JefeAlmacen")
                        .WithMany()
                        .HasForeignKey("JefeAlmacenId");

                    b.Navigation("DepartamentoDestino");

                    b.Navigation("JefeAlmacen");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaMedicamentoDetalle", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.EntregaMedicamento", "Entrega")
                        .WithMany("Detalles")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Medicamento", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Stock", null)
                        .WithMany("Medicamentos")
                        .HasForeignKey("StockIdStock");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.PedidoMedicamento", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.PedidoMedicamentoDetalle", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.PedidoMedicamento", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.SolicitudMedicamento", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.Trabajador", "JefeDepartamento")
                        .WithMany()
                        .HasForeignKey("JefeDepartamentoId");

                    b.Navigation("Departamento");

                    b.Navigation("JefeDepartamento");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.SolicitudMedicamentoDetalle", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Policlínico.Domain.Entities.SolicitudMedicamento", "Solicitud")
                        .WithMany("Detalles")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Stock", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Departamento", "Departamento")
                        .WithOne("Stock")
                        .HasForeignKey("Policlínico.Domain.Entities.Stock", "DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Trabajador", b =>
                {
                    b.HasOne("Policlínico.Domain.Entities.Consulta", null)
                        .WithMany("Doctores")
                        .HasForeignKey("ConsultaIdConsulta");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Consulta", b =>
                {
                    b.Navigation("AsignacionesConsulta");

                    b.Navigation("Doctores");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaAConsulta", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.EntregaMedicamento", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.PedidoMedicamento", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.SolicitudMedicamento", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Stock", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Policlínico.Domain.Entities.Trabajador", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("AsignacionesConsulta");
                });
#pragma warning restore 612, 618
        }
    }
}
